# Generated by Django 3.0.4 on 2020-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('description', models.TextField(default='')),
                ('time', models.TimeField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('date', models.DateField(null=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
